version: "3"

services:
  ui:
    image: ghcr.io/${GH_USERNAME}/ui-stg:${UI_VERSION}
    container_name: ui
    build:
      context: ./ui
      dockerfile: stg.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000
    networks:
      - nextjs_laravel

networks:
  nextjs_laravel:
    external: true
