version: "3"

services:
  ui:
    container_name: ui
    image: ghcr.io/${GH_USERNAME}/ui-dev:${UI_VERSION}
    build:
      context: ./ui
      dockerfile: dev.Dockerfile

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./ui/src:/app/src
      - ./ui/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - nextjs_laravel

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  nextjs_laravel:
    external: true
