version: "3"

services:
  ui:
    image: ghcr.io/marloeleven/ui-prod:latest
    container_name: ui
    build:
      context: ./ui
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)
networks:
  my_network:
    external: true
