name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login --username ${{ secrect.GH_USERNAME }} --password ${{ secrect.GH_TOKEN }} ghcr.io
        docker compose -f ./../../docker-compose.prod.yml build
        docker push ghcr.io/${{ secrect.GH_USERNAME }}/ui-prod:latest
