name: Docker Image CI

on:
  push:
    branches: ["master"]

env:
  ID_RSA: ${{ secrets.ID_RSA }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  IMAGE: ghcr.io/${{ secrets.GH_USERNAME }}/ui-prod:latest

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Build the Docker image
  #       run: |
  #         docker login --username ${{ secrets.GH_USERNAME }} --password ${{ secrets.GH_TOKEN }} ghcr.io
  #         docker compose -f ./docker-compose.prod.yml build
  #         docker push ghcr.io/${{ secrets.GH_USERNAME }}/ui-prod:latest

  deploy:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ID_RSA }}
      - name: Install SSH key and SSH into VPS and execute Docker commands
        run: |
          ssh -o StrictHostKeyChecking=no -i "$ID_RSA" $SERVER_USER@$SERVER_IP "su - github && docker login --username ${{ secrets.GH_USERNAME }} --password ${{ secrets.GH_TOKEN }} ghcr.io"
